# The URL the site will be built for
base_url = "https://artemchandragupta.github.io"

#Title
title = "artem::scriptorium"
description = ""
author = "artemchandragupta"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# make lists according to assigned tags
taxonomies = [
    {name = "writings", feed = true, paginate_by = 12},
]

[search]
include_title = true
include_description = false
include_path = false
include_content = true

[markdown.highlighting]
theme = "gruvbox-dark-medium"

[extra]
author = "artemchandragupta"
email = "artem020503@gmain.com"
profile = "/logo/thumbnail.png"

github_user = "artemchandragupta"
